#! /bin/sh

###############################
### CONFIGURAÇÕES DO INÍCIO ###
###############################

# Inicia o polybar
$HOME/.config/polybar/launch.sh &

# Configuração da janela polybar
xdo -N raise "principal"

# Configura as teclas de atalho
pgrep -x sxhkd > /dev/null || sxhkd &

# Configura o teclado
setxkbmap -model abnt2 -layout br -variant abnt2 &

# Inicia o compositor
picom --experimental-backends &

# Background
hsetroot -solid "#070E13" &

## Configura o monitor 
bspc monitor -d 1 2 3 4 5 6 7 8 9 &

##################################
### MINHAS CONFIGURAÇÕES BSPWM ###
##################################

bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          35
bspc config bottom_padding       0
bspc config left_padding         3
bspc config right_padding        3
bspc config single_monocle       false
bspc config click_to_focus       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

## BSPWM CORES ##
bspc config normal_border_color 	"#414851"
bspc config active_border_color 	"#528BBB"
bspc config focused_border_color 	"#528BBB"
bspc config presel_feedback_color 	"#528BBB"

##############################
### CONFIGURAÇÕES DOS APPS ###
##############################

